spring.datasource.url=jdbc:postgresql://localhost:5432/dataprocessor
spring.datasource.username=dataprocessor
spring.datasource.password=dataprocessor

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true