spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/dataprocessor}
spring.datasource.username=${DB_USER:dataprocessor}
spring.datasource.password=${DB_PASSWORD:dataprocessor}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true